name: Deploy specification

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: npm ci
      - run: npm run build
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Deploy to branch
        run: |
          git checkout -b assembled-spec
          git add -f openrpc.json
          git add -f refs-openrpc.json
          git commit -m "assemble openrpc.json"
          git push -fu origin assembled-spec
